name: Inkeep Source Sync

on:
  push:
    branches:
      - canary
    paths:
      - 'docs/**'
    
jobs:
  syncSourceJob:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check for changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            docs:
              - 'docs/**'
      - name: Sync Docs Source 
        if: steps.changes.outputs.docs == 'true'
        uses: inkeep/pr-commenter-action@v10
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          apiKey: ${{ secrets.INKEEP_API_KEY }}
          sourceId: 'clpsnwsrk000ws601znjvmgkh'
        